### ISSUE TITLE
timestamp calculations possible?

### ISSUE THREAD

**Issue by jo-me** [custom-cards/secondaryinfo-entity-row#18] opened 2019-09-13 19:12 UTC
Hi,

I tried to set the color of the  secondary info line based on the age of a certain timestamp.

```
      <b style='color:[[ if(as_timestamp({entity}.attributes.receivedTS) -
      as_timestamp(now()) < 14400, "green", "red") ]]'>[[
```

This results in red text because the "as_timestamp" method is not evaluated and therefore the result is not a number. 

Is it possible to use the as_timestamp function or someting similar somehow?

**Comment by Mariusthvdb** [comment] 2019-11-15 16:26
+1 would be very nice indeed to have the secondary-line show the timestamp of last_changed and last_updated, and of attributes.last_triggered

this is a bit awkward:

![Schermafbeelding 2019-11-15 om 17 25 31](https://user-images.githubusercontent.com/33354141/68958746-fbf3c080-07cc-11ea-9405-013448b8b93c.png)
;-)

thanks for considering!

**Comment by iantrich** [comment] 2020-01-31 14:59
it does not support jinja. I create template sensors for relative time

**Comment by iantrich** [comment] 2020-01-31 15:01
duplicate of https://github.com/custom-cards/secondaryinfo-entity-row/issues/2

**Closed by iantrich** 2020-01-31 15:01 UTC
